/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OnlineBillingSystems;

/**
 *
 * @author fjohn
 */
public class BillingSystems extends javax.swing.JFrame {
    
    double firstNum;
    double secondNum;
    double result;
    String answer;
    String operations;
    double Labour = 40;
    double Travel = 3;
    double Plastic = 5.5;
    double Copper = 7.5;
    double Chrome = 8.5;
    double iTax = 7.5;
            

    /**
     * Creates new form BillingSystems
     */
    public BillingSystems() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textFieldCalculator = new javax.swing.JTextField();
        number4 = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        buttonDecimal = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        buttonAddition = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        buttonMultiply = new javax.swing.JButton();
        buttonDivide = new javax.swing.JButton();
        buttonSubtract = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        number0 = new javax.swing.JButton();
        buttonEquals = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        checkBoxLabour = new javax.swing.JCheckBox();
        checkBoxTravel = new javax.swing.JCheckBox();
        checkBoxPlastic = new javax.swing.JCheckBox();
        checkBoxCopper = new javax.swing.JCheckBox();
        checkBoxChrome = new javax.swing.JCheckBox();
        labelCostItems = new javax.swing.JLabel();
        labelCostDelivery = new javax.swing.JLabel();
        labelCostMileage = new javax.swing.JLabel();
        checkBoxTax = new javax.swing.JCheckBox();
        checkBoxVAT = new javax.swing.JCheckBox();
        textFieldCostItems = new javax.swing.JTextField();
        textFieldCheckBoxTax = new javax.swing.JTextField();
        textFieldVAT = new javax.swing.JTextField();
        textFieldLabour = new javax.swing.JTextField();
        textFieldTravel = new javax.swing.JTextField();
        textFieldPlastic = new javax.swing.JTextField();
        textFieldCopper = new javax.swing.JTextField();
        textFieldChrome = new javax.swing.JTextField();
        textFieldCostDelivery = new javax.swing.JTextField();
        textFieldCostMileage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        labelTax = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        labelTotalAmount = new javax.swing.JLabel();
        textFieldSubTotal = new javax.swing.JTextField();
        textFieldTotalAmount = new javax.swing.JTextField();
        textFieldTax = new javax.swing.JTextField();
        buttonClear = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();
        buttonCalculate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        textFieldCalculator.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textFieldCalculator.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        number4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });

        number3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });

        number1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });

        number5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });

        number6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });

        number7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });

        number8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number8.setText("8");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });

        buttonDecimal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonDecimal.setText(".");
        buttonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDecimalActionPerformed(evt);
            }
        });

        buttonC.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonC.setText("C");
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonAddition.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonAddition.setText("+");
        buttonAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdditionActionPerformed(evt);
            }
        });

        number2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });

        buttonMultiply.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonMultiply.setText("*");
        buttonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultiplyActionPerformed(evt);
            }
        });

        buttonDivide.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonDivide.setText("/");
        buttonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivideActionPerformed(evt);
            }
        });

        buttonSubtract.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonSubtract.setText("-");
        buttonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubtractActionPerformed(evt);
            }
        });

        number9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });

        number0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        number0.setText("0");
        number0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number0ActionPerformed(evt);
            }
        });

        buttonEquals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonEquals.setText("=");
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldCalculator)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textFieldCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(number9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(number0, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkBoxLabour.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxLabour.setText("Labour");
        checkBoxLabour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxLabourActionPerformed(evt);
            }
        });

        checkBoxTravel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxTravel.setText("Travel");
        checkBoxTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTravelActionPerformed(evt);
            }
        });

        checkBoxPlastic.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxPlastic.setText("Plastic");

        checkBoxCopper.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxCopper.setText("Copper");

        checkBoxChrome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxChrome.setText("Chrome");

        labelCostItems.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCostItems.setText("Total Cost of Items");

        labelCostDelivery.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCostDelivery.setText("Total Cost of Delivery");

        labelCostMileage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelCostMileage.setText("Total Cost of Mileage");

        checkBoxTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxTax.setText("Tax");

        checkBoxVAT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        checkBoxVAT.setText("VAT");

        textFieldCheckBoxTax.setToolTipText("");

        textFieldCostDelivery.setToolTipText("");

        textFieldCostMileage.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxPlastic)
                        .addGap(35, 35, 35)
                        .addComponent(textFieldPlastic))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxTravel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxLabour)
                        .addGap(31, 31, 31)
                        .addComponent(textFieldLabour, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxCopper)
                            .addComponent(checkBoxChrome))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldChrome)
                            .addComponent(textFieldCopper))))
                .addGap(83, 83, 83)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCostDelivery)
                            .addComponent(labelCostItems)
                            .addComponent(labelCostMileage))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(checkBoxVAT)
                            .addGap(180, 180, 180)))
                    .addComponent(checkBoxTax))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldCheckBoxTax, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCostItems, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCostDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCostMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxLabour)
                    .addComponent(labelCostItems)
                    .addComponent(textFieldCostItems, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldLabour, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxTravel)
                    .addComponent(textFieldTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCostDelivery)
                    .addComponent(textFieldCostDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkBoxPlastic)
                            .addComponent(textFieldPlastic, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCostMileage)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(textFieldCostMileage, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxCopper)
                    .addComponent(checkBoxTax)
                    .addComponent(textFieldCheckBoxTax, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCopper, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxChrome)
                    .addComponent(checkBoxVAT)
                    .addComponent(textFieldVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldChrome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Online Billing Systems");

        labelTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTax.setText("Tax");

        labelSubTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelSubTotal.setText("Sub Total");

        labelTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTotalAmount.setText("Total Amount");

        textFieldSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSubTotalActionPerformed(evt);
            }
        });

        buttonClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonClear.setText("Clear");
        buttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClearActionPerformed(evt);
            }
        });

        buttonReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonReset.setText("Reset");
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        buttonCalculate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTax, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldTotalAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(387, 387, 387))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubTotal)
                    .addComponent(buttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldTax, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTax)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textFieldTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTotalAmount))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxLabourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxLabourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxLabourActionPerformed

    private void checkBoxTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxTravelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxTravelActionPerformed

    private void buttonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubtractActionPerformed
        firstNum = Double.parseDouble(textFieldCalculator.getText());
        textFieldCalculator.setText("");
        operations = "-";
    }//GEN-LAST:event_buttonSubtractActionPerformed

    private void buttonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDivideActionPerformed
        firstNum = Double.parseDouble(textFieldCalculator.getText());
        textFieldCalculator.setText("");
        operations = "/";
    }//GEN-LAST:event_buttonDivideActionPerformed

    private void buttonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMultiplyActionPerformed
        firstNum = Double.parseDouble(textFieldCalculator.getText());
        textFieldCalculator.setText("");
        operations = "*";
    }//GEN-LAST:event_buttonMultiplyActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        String enterValue = textFieldCalculator.getText() + number2.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number2ActionPerformed

    private void buttonAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdditionActionPerformed
        firstNum = Double.parseDouble(textFieldCalculator.getText());
        textFieldCalculator.setText("");
        operations = "+";
    }//GEN-LAST:event_buttonAdditionActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        textFieldCalculator.setText("");
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDecimalActionPerformed
        String enterValue = textFieldCalculator.getText() + buttonDecimal.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_buttonDecimalActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        String enterValue = textFieldCalculator.getText() + number8.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number8ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        String enterValue = textFieldCalculator.getText() + number7.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number7ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        String enterValue = textFieldCalculator.getText() + number6.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number6ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        String enterValue = textFieldCalculator.getText() + number5.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number5ActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        String enterValue = textFieldCalculator.getText() + number1.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number1ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        String enterValue = textFieldCalculator.getText() + number3.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number3ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        String enterValue = textFieldCalculator.getText() + number4.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number4ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        String enterValue = textFieldCalculator.getText() + number9.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number9ActionPerformed

    private void number0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number0ActionPerformed
        String enterValue = textFieldCalculator.getText() + number0.getText();
        textFieldCalculator.setText(enterValue);
    }//GEN-LAST:event_number0ActionPerformed

    private void buttonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEqualsActionPerformed
        secondNum = Double.parseDouble(textFieldCalculator.getText());
        if (operations == "+") {
            result = firstNum + secondNum;
            answer = String.format("%.0f", result);
            textFieldCalculator.setText(answer);
        }
        else if (operations == "-") {
            result = firstNum - secondNum;
            answer = String.format("%.0f", result);
            textFieldCalculator.setText(answer);
        }
        else if (operations == "*") {
            result = firstNum * secondNum;
            answer = String.format("%.0f", result);
            textFieldCalculator.setText(answer);
        }
        else if (operations == "/") {
            result = firstNum / secondNum;
            answer = String.format("%.0f", result);
            textFieldCalculator.setText(answer);
        }
    }//GEN-LAST:event_buttonEqualsActionPerformed

    private void buttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClearActionPerformed
        textFieldLabour.setText("");    // 1
        textFieldTravel.setText("");    // 2
        textFieldCalculator.setText("");    // 3
        textFieldPlastic.setText("");   // 4
        textFieldCopper.setText("");    // 5
        textFieldChrome.setText("");    // 6
        textFieldCostItems.setText(""); // 7
        textFieldCostDelivery.setText("");  // 8
        textFieldCostMileage.setText("");   // 9
        textFieldCheckBoxTax.setText("");   // 10
        textFieldVAT.setText("");           // 11
        textFieldSubTotal.setText("");      // 12
        textFieldTax.setText("");       // 13
        textFieldTotalAmount.setText("");   // 15
    }//GEN-LAST:event_buttonClearActionPerformed

    private void textFieldSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSubTotalActionPerformed

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        try {
            double l = Double.parseDouble(textFieldLabour.getText());
            double t = Double.parseDouble(textFieldTravel.getText());
            double p = Double.parseDouble(textFieldPlastic.getText());
            double c = Double.parseDouble(textFieldCopper.getText());
            double ch = Double.parseDouble(textFieldChrome.getText());
            
            double r;
            double v;
            double m;
            double i;
            double x;
            double total;
            
            if (!(checkBoxLabour.isSelected()) && !(checkBoxTravel.isSelected())) {
                textFieldLabour.setText("");    // 1
                textFieldTravel.setText("");    // 2
                textFieldCalculator.setText("");    // 3
                textFieldPlastic.setText("");   // 4
                textFieldCopper.setText("");    // 5
                textFieldChrome.setText("");    // 6
                textFieldCostItems.setText(""); // 7
                textFieldCostDelivery.setText("");  // 8
                textFieldCostMileage.setText("");   // 9
                textFieldCheckBoxTax.setText("");   // 10
                textFieldVAT.setText("");           // 11
                textFieldSubTotal.setText("");      // 12
                textFieldTax.setText("");       // 13
                textFieldTotalAmount.setText("");   // 15
                textFieldCalculator.setText("Make a Selection Now!");
            }
            if (checkBoxPlastic.isSelected()) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic));
                String result = String.format("%.2f", r);
                textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
            }
            if (checkBoxCopper.isSelected()) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic));
                String result = String.format("%.2f", r);
                textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
            }
            if (checkBoxChrome.isSelected()) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic));
                String result = String.format("%.2f", r);
                textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
            }
            if ((checkBoxPlastic.isSelected()) && (checkBoxCopper.isSelected())) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic) + (c * Copper));
                String result = String.format("%.2f", r);
                textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
            }
            if ((checkBoxPlastic.isSelected()) && (checkBoxCopper.isSelected()) && (checkBoxChrome.isSelected())) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic) + (c * Copper) + (ch * Chrome));
                String result = String.format("%.2f", r);
                textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
            }
            if ((checkBoxTax.isSelected()) || (checkBoxVAT.isSelected())) {
                r = ((l * Labour) + (t * Travel) + (p * Plastic) + (c * Copper) + (ch * Chrome));
                String result = String.format("%.2f", r);
                //textFieldTotalAmount.setText(result);
                v = (l * Labour);
                m = (t * Travel);
                i = ((p * Plastic) + (c * Copper) + (ch * Chrome));
                String job = String.format("%.2f", v);
                String miles = String.format("%.2f", m);
                String items = String.format("%.2f", m);
                textFieldCostItems.setText(items);
                textFieldCostDelivery.setText(job);
                textFieldCostMileage.setText(miles);
                textFieldTax.setText(result);
                
                double tax = Double.parseDouble(textFieldTax.getText());
                x = ((r * iTax) / 100);
                total = (r + x);
                String VATTax = String.format("%2f", x);
                String totalCost = String.format("%2f", total);
                textFieldCheckBoxTax.setText(VATTax);
                textFieldVAT.setText(VATTax);
                textFieldSubTotal.setText(VATTax);
                textFieldTotalAmount.setText(totalCost);
            }
        }
        catch (NumberFormatException e) {
                    textFieldCalculator.setText("Make a Selection Now!");
                    }
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        textFieldSubTotal.setText("");
        textFieldTax.setText("");
        textFieldTotalAmount.setText("");
        textFieldLabour.setText("");
        textFieldTravel.setText("");
        textFieldPlastic.setText("");
        textFieldCopper.setText("");
        textFieldChrome.setText("");
        textFieldCostItems.setText("");
        textFieldCostDelivery.setText("");
        textFieldCostMileage.setText("");
        textFieldCheckBoxTax.setText("");
        textFieldVAT.setText("");
        textFieldCalculator.setText("");
    }//GEN-LAST:event_buttonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingSystems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingSystems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddition;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonClear;
    private javax.swing.JButton buttonDecimal;
    private javax.swing.JButton buttonDivide;
    private javax.swing.JButton buttonEquals;
    private javax.swing.JButton buttonMultiply;
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonSubtract;
    private javax.swing.JCheckBox checkBoxChrome;
    private javax.swing.JCheckBox checkBoxCopper;
    private javax.swing.JCheckBox checkBoxLabour;
    private javax.swing.JCheckBox checkBoxPlastic;
    private javax.swing.JCheckBox checkBoxTax;
    private javax.swing.JCheckBox checkBoxTravel;
    private javax.swing.JCheckBox checkBoxVAT;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCostDelivery;
    private javax.swing.JLabel labelCostItems;
    private javax.swing.JLabel labelCostMileage;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTax;
    private javax.swing.JLabel labelTotalAmount;
    private javax.swing.JButton number0;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JTextField textFieldCalculator;
    private javax.swing.JTextField textFieldCheckBoxTax;
    private javax.swing.JTextField textFieldChrome;
    private javax.swing.JTextField textFieldCopper;
    private javax.swing.JTextField textFieldCostDelivery;
    private javax.swing.JTextField textFieldCostItems;
    private javax.swing.JTextField textFieldCostMileage;
    private javax.swing.JTextField textFieldLabour;
    private javax.swing.JTextField textFieldPlastic;
    private javax.swing.JTextField textFieldSubTotal;
    private javax.swing.JTextField textFieldTax;
    private javax.swing.JTextField textFieldTotalAmount;
    private javax.swing.JTextField textFieldTravel;
    private javax.swing.JTextField textFieldVAT;
    // End of variables declaration//GEN-END:variables
}
